### ISSUE TITLE
Possible bug with JUNIT file

### ISSUE THREAD

**Issue by SimonHellings** [codykonior/Jojoba#2]
I have been runnning Jenkins with PowerShell for over 6 months now with great success and results (Kudos; very impressed, thank you for sharing!).

I updated some plugins today and started to get failures of the jobs themselves, not just the tests.

One of the plugins updated was XUNIT.

On invesigation into the console output it appears that the problem is with the format of the JUNIT file.  See below (I have cut some of the duplicates for brevity):

`INFO: [JUnit] - 1 test report file(s) were found with the pattern 'Jojoba.xml' relative to 'C:\Program Files (x86)\Jenkins\workspace\Test-Autoshrink' for the testing framework 'JUnit'.`
`WARNING: The file 'C:\Program Files (x86)\Jenkins\workspace\Test-Autoshrink\Jojoba.xml' is an invalid file.`
`WARNING: At line 2 of file:/C:/Program%20Files%20(x86)/Jenkins/workspace/Test-Autoshrink/Jojoba.xml:cvc-complex-type.4: Attribute 'failures' must appear on element 'testsuite'.`
`WARNING: At line 2 of file:/C:/Program%20Files%20(x86)/Jenkins/workspace/Test-Autoshrink/Jojoba.xml:cvc-complex-type.4: Attribute 'errors' must appear on element 'testsuite'.`
`WARNING: At line 3 of file:/C:/Program%20Files%20(x86)/Jenkins/workspace/Test-Autoshrink/Jojoba.xml:cvc-complex-type.3.2.2: Attribute 'timestamp' is not allowed to appear in element 'testcase'.`
`WARNING: At line 4 of file:/C:/Program%20Files%20(x86)/Jenkins/workspace/Test-Autoshrink/Jojoba.xml:cvc-complex-type.3.2.2: Attribute 'timestamp' is not allowed to appear in element 'testcase'.`
`.`
`.`
`.`
`WARNING: At line 72 of file:/C:/Program%20Files%20(x86)/Jenkins/workspace/Test-Autoshrink/Jojoba.xml:cvc-complex-type.3.2.2: Attribute 'timestamp' is not allowed to appear in element 'testcase'.`
`ERROR: The plugin hasn't been performed correctly: The result file 'C:\Program Files (x86)\Jenkins\workspace\Test-Autoshrink\Jojoba.xml' for the metric 'JUnit' is not valid. The result file has been skipped.`
`Build step 'Publish xUnit test result report' changed build result to FAILURE`
`Email was triggered for: Failure - Any`
`Sending email for trigger: Failure - Any`
`Sending email to: xxx@xxx.com`
`Finished: FAILURE`

I had a quick look at the plugin's documentation page and that confirms that there is a potentially breaking change in 2.0.0 where schema validation is now applied.

`failures` and `errors` is missing from the `testsuite` element and `timestamp` is no longer allow in the `testcase` element.

https://wiki.jenkins.io/display/JENKINS/xUnit+Plugin

I tried downloading the updated version of Jojoba (from 1.4.0.3 to 4.0.8).  This required a few code changes to my functions, but nothing major in the hope that the schema changes have been applied but it doesn't look like it to date.

I  have partially updated my copy of `Write-JojobaXml.ps1` (it calculates failures, but there is no error logic in there) but I don't know much about Github to be able to push this back to you for verification should you wish to have these changes.

**Comment by codykonior** [comment]
Thanks for letting me know! I will try it out and push a fix for this in the next few days.

**Comment by codykonior** [comment]
I reproduced the problem and this fix seems to work. It has been pushed to the powershell gallery and I’ll close this issue in a week once it has burnt in.

**Comment by SimonHellings** [comment]
Hi Cody

Thanks for the feedback and quick resolution.

I will download this shortly and come back to you if I come across any problems.

(not sure how this closed; I only tried to write this comment!)

**Comment by SimonHellings** [comment]
This appears to have been working fine for me so am happy to close this off.  Thanks again Kody!
